#!/usr/bin/bash
#
# Update a plugin with new shipdriver templates.
#
# usage: ./update-templates [treeish]
#
# Merge changes from upstream shipdriver repo into
# current branch.
#
# See UPDATE-TEMPLATES.md for more info

source_treeish=${1:-"shipdriver/master"}

# Refuse to run unless the index is clean:
clean=$(git status --porcelain | grep -v update-template)
if [ -n "$clean" ]; then 
    echo "Please commit or stash pending changes. Aborting."
    exit 1
fi

# Set up the shipdriver remote
if git ls-remote --exit-code shipdriver &>/dev/null; then
    git remote remove shipdriver
    echo "Removing existing shipdriver remote."
fi
git remote add shipdriver https://github.com/Rasbats/shipdriver_pi.git
git remote update shipdriver
git fetch --tags shipdriver

# Merge all changes in shipdriver remote with current branch
git merge --no-ff --no-commit --allow-unrelated-histories -X theirs \
    $source_treeish

# Restore all non-template files.
for f in \
    CMakeLists.txt \
    build-deps \
    buildosx \
    buildwin \
    config.h.in \
    COPYING \
    data \
    flatpak \
    libs \
    manual \
    mingw \
    po \
    README.md \
    src
do
    if test -e "$f"; then git checkout HEAD $f; fi
    # Remove all added files in local directories
    for ff in $(git status --porcelain $f \
                | grep -E "A? $f" | awk '{print $2}')
    do
        git rm --quiet -f $ff
    done
done

# Remove miscellaneous added files
for f in $(git status --porcelain \
           | grep -E "A.*enc|A.*pub|A.*fbp" \
           | awk '{print $2}')
do
    git rm -f --quiet $f
done

# Revert changes in blacklisted files.
if [ -e update-ignored ]; then
    for f in $(cat update-ignored); do
        git checkout HEAD $f
    done
fi

# Create or update version file
date  "+%Y-%m-%d %H:%M" > cmake/TemplateVersion
commit=$(git rev-parse --short $source_treeish)
echo "commit: $commit" >> cmake/TemplateVersion
tags=$(git tag --contains $commit)
echo "tags: $tags" >> cmake/TemplateVersion
git add cmake/TemplateVersion


cat << EOF
Shipdriver templates have been updated. To review pending changes:

    $ git status
    $ git diff --staged

See UPDATE_TEMPLATES.md for more.
EOF
