:imagesdir: ../images/
== Hardware installation Navico

The Navico radars are very easy to use with OpenCPN. All you need is a
wired Ethernet connection.

You can add as many computers as desired, the system will allow
operation from all connected MFDs (plotters) and computers.

= RI10/11

In all Broadband installation packages (except Lowrance 3G USA) the
scanner also ships with a small black box – either a RI10 with NMEA 2000
input or a RI11 with NMEA 0183. It uses the data from the heading sensor
on the NMEA network to add this to the radar data.

* The Navico plotters require heading input to the RI-10/11 for MARPA
operation.
* The plugin uses this heading as the "best" source of heading for
radar overlay.

This box also helps isolating the system electrically, and will improve
protection of the computer from damage in case of electrical storms
(lightning.)

Note that this box is no longer needed with HALO radomes. HALO 4/6/8
apparently come with an interface box, but they don’t inject heading we
think.

= Shared setup with a Navico MFD

If you already have a Navico MFD installed the installation consists of:

* Installing an Ethernet switch, or a WiFi router with a built in
Ethernet switch. You need a wired port for each device – the radar, the
MFD(s) and the computer running OpenCPN.
* Connect all devices to the switch.

For HALO radars which come with a RJ45 at the end of the radar cable and
a RJ45 to Yellow Navico converter cable, you can plug the radar cable
into a standard switch directly, and use a standard RJ45 patch cable to
connect the converter cable to the switch as well.

If your radar did not come with a RJ45 to Navico radar connector cable,
like the 3G or 4G, you can either buy one or make yourself. The cheapest
solution is to cut Navico Ethernet cables with two yellow connectors at
both ends, and crimp a RJ45 connector onto both halves.

Follow the instructions here to fabricate these:
http://yachtelectronics.blogspot.nl/2010/05/lowrance-yellow-ethernet-cabling.html.

So for the case where you have a single MFD connected to a 3G/4G radar
scanner: _Cut the ethernet cable between MFD and scanner. Crimp on
two RJ45 connectors. Insert these into a switch._ Connect the
computer to the switch as well.

= Installation with only a scanner

If your scanner came with a RI10: _Cut the supplied Navico ethernet
cable in half. Crimp on a RJ45 connector. Insert the RJ45 connector
into the computer’s Ethernet port or a standard Ethernet switch and the
other side into the RI10._ Install the scanner as detailed in the Navico
installation instructions.

If you bought a HALO or USA Lowrance 3G scanner:

* Insert the RJ45 connector from the radar scanner into a standard 100
Mbit switch.

We recommend always using an ethernet switch in this setup to provide
further electrical isolation between the scanner and the computer – this
makes your computer safer in case of lightning. If you connect the
computer directly to the radar scanner it will work but you have a higher 
chance of lightning ruining your computer.

= Network setup

The scanner and the displays communicate using a system called
_multicast_. This has the advantage that the data only needs to be sent
once, and is received by all displays. Uniquely, it also means that
there is no issue with IP addresses, so there is no reliance on DHCP
working. _Any IP address is acceptable for all Navico radars._

== Choosing an Ethernet switch

If you are going to use a switch you may as well use a Gigabit switch.
The scanner has a 100 Mbit interface, but a Gigabit switch will use
slightly less power than a 100 MBit switch. You should probably also use
one that has a 12V input which can be powered directly from the 12V
house battery (or a DC/DC converter if you have a 24 V house battery
bank.)

The author uses a 5 port Netgear GS105 which according to Netgear: _Both
GS105 and GS108 support the latest Energy E cient Ethernet (IEEE
802.3az) standard, which reduces energy consumption when there is light
traffic on an active port or when there is no link or no activity
detected. It can further save energy when a short cable (<100m) is used.
Energy savings lead directly to cost savings in operation._

Note: make sure you get the _metal cased_ GS105/GS108 that uses 12 V
input. There are now also other models with a plastic case that have a 5
V input, which requires an extra DC/DC converter.

== WiFi

The _multicast_ transmission system used by the scanner means that
transmission over WiFi must happen at the lowest rate that any device
connected to the WiFi network is capable of. For 802.11b and g this rate
is 1 Mbit/s. Since the radar data is \~1 Mbit/s as well this means it
_does not work well at all_.

The solution is to either: * Modify the base rate to be higher. This
reduces the maximum range of your WiFi network for all devices. * Get a
faster WiFi network, for example 802.11a or 802.1ac (5 GHz). This has a
much faster base rate (6 Mbit/s).

Unfortunately, most WiFi routers do not allow you to change the base
rate.

If yours is Linux based and uses "hostapd" you can try the following
procedure. Edit the following section in "hostapd.conf". The example
_should_ disable basic rates 10 and 20 (= 1 and 2 Mbit/s):

....
#Basic rate set configuration
#List of rates (in 100 kbps) that are included in the basic rate set.
#If this item is not included, usually reasonable default set is used.
#basic_rates=10 20
#basic_rates=10 20 55 110
#basic_rates=55 110
#basic_rates=60 120 240
....

The author has had no success with trying the above as the `hostapd` he
is using seems to ignore these instructions, and has resorted to using a
5 GHz network instead. Even that gets seriously loaded by broadcast
traffic generated by the Navico MFDs.

xref:Home.adoc[Back to overview Plugin radar_pi]
