:imagesdir: ../images/
== Requirements
The plugin has very few hard requirements nowadays, but the
functionality does increase with more sensors. Let’s start with a
minimal setup and grow this step by step, and see what functionality is
enabled by these steps.

== Radar scanner

It won’t come as a surprise to you that you need a supported radar
scanner. If you buy new, we recommend the Navico HALO. It has better
definition and more features than the Garmin xHD and the older Navico
radars, and we don’t support new Garmin or other brand radars yet.

If you buy secondhand make sure the radar is still working. Like all
radome antennas they are susceptible to moisture and not all of them
will live to be 20 years old! The lifetime of a magnetron is 2000-4000
hours. Digital radars just die of old age.

== Compass heading

The plugin requires a compass heading to be able to show the radar image
in stabilized, COG up or North up mode. If there is no compass heading
it will just show the radar image as received from the scanner, and the
image will not be correct during turns or heavy sea conditions that
induce yaw.

The higher the compass rate the better the picture will be in difficult
circumstances. With Navico Broadband BR24/3G/4G radars use of an
RI-10/11 will improve the picture as well, as the heading in use at the
moment of creating the spoke (a ray of radar data in a particular
direction) is stored with the data.

== GPS/GNSS location

The plugin requires a GNSS location (usually GPS) to be able to draw the
radar image over the chart (_overlay_). By default it also requires a
compass heading, as COG is not useful at low speeds. There is a setting
that allows the use of COG for overlay, but it does mean that the radar
overlay is not useful at anchor or other zero/low speed situations. 
Also is the COG affected by leeway and currents and may point sideways 
leading to a misplaced overlay picture.

xref:index.adoc[Back to overview Plugin radar_pi]
