
#ifndef RAYMARINE_SPOKES
#define RAYMARINE_SPOKES 2048
#endif

#ifndef RAYMARINE_SPOKE_LEN
#define RAYMARINE_SPOKE_LEN 1024
#endif

#if SPOKES_MAX < RAYMARINE_SPOKES
#undef SPOKES_MAX
#define SPOKES_MAX NAVICO_SPOKES
#endif
#if SPOKE_LEN_MAX < RAYMARINE_SPOKE_LEN
#undef SPOKE_LEN_MAX
#define SPOKE_LEN_MAX NAVICO_SPOKE_LEN
#endif
