#!/bin/sh
#
# The standard  pre-commit which comes with git with some additions.
#
# To enable this hook on non-windows platforms:
#      $ cd .git/hooks; ln -s ../../scripts/pre-commit .
#
# On Windows, with administrative or developer mode privileges and in
# a native CMD window (not git-bash):
#      > cd .git/hooks; mklink pre-commit ..\..\scripts\pre-commit
#
# Otherwise on Windows (the symlink is preferred):
#      > cp pre-commit ..\.git/hooks


if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.
This can cause problems if you want to work with people on other platforms.
To be portable it is advisable to rename the file.
If you know what you are doing you can disable this check using:
  git config hooks.allownonascii true
EOF
	exit 1
fi

# Ensure that .sh files has executable permissions
for f in $(git diff-index --cached --diff-filter=ACMR HEAD); do
    if [[ $f != *.sh ]]; then continue; fi
    set -- $(ls -l $f)
    perms=$1
    if [ "$perms" = "${perms##*x}" ]; then
        echo "Error: $f is not executable, but .sh files should be"
	exit 1
    fi
done

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
