/* Autogenerated by png2wx.pl on Fri Dec  1 10:51:37 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_ShipDriverIcon;

#ifdef SHIPDRIVER_USE_SVG
extern wxString _svg_shipdriver;
extern wxString _svg_shipdriver_toggled;
#endif

#endif /* ICONS_H */
