set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 21)
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
if (DEFINED ENV{NDK_HOME})
  set(CMAKE_ANDROID_NDK $ENV{NDK_HOME})
else ()
  set(CMAKE_ANDROID_NDK /opt/android/ndk)
endif ()
set(ARM_ARCH armhf CACHE STRING "Selected arm architecture" FORCE)
